[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build" # Removed 'npm install' as Netlify handles this automatically

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200