import jsPDF from "jspdf";
import "jspdf-autotable";

export const generateMonthlyReport = (restaurantName, historyData, expenses, dishes) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // 1. Header & Branding
    doc.setFontSize(22);
    doc.setTextColor(249, 115, 22); // Your brand orange
    doc.text(restaurantName.toUpperCase(), 14, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Monthly Business Analytics Report | Generated: ${date}`, 14, 28);
    doc.line(14, 32, 196, 32);

    // 2. Financial Summary Box
    const totalRevenue = historyData.reduce((s, o) => s + (o.totalAmount || 0), 0);
    const totalExpenses = expenses.reduce((s, e) => s + (e.amount || 0), 0);
    const profit = totalRevenue - totalExpenses;

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("FINANCIAL SUMMARY", 14, 45);
    
    doc.autoTable({
        startY: 50,
        head: [['Metric', 'Amount (INR)']],
        body: [
            ['Total Sales Revenue', `Rs. ${totalRevenue.toLocaleString()}`],
            ['Total Operating Expenses', `Rs. ${totalExpenses.toLocaleString()}`],
            ['Net Monthly Profit', `Rs. ${profit.toLocaleString()}`],
        ],
        theme: 'striped',
        headStyles: { fillColor: [40, 40, 40] }
    });

    // 3. Top Selling Dishes
    const finalY = doc.lastAutoTable.finalY + 15;
    doc.text("TOP PERFORMING DISHES", 14, finalY);

    const dishStats = dishes.map(dish => {
        const salesCount = historyData.filter(order => 
            order.items.some(item => item.name === dish.name)
        ).length;
        return [dish.name, dish.category, salesCount, `Rs. ${dish.price * salesCount}`];
    });

    doc.autoTable({
        startY: finalY + 5,
        head: [['Dish Name', 'Category', 'Orders', 'Total Revenue']],
        body: dishStats,
        headStyles: { fillColor: [249, 115, 22] }
    });

    // 4. Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by Smart Menu Cloud Node v2.8", 14, doc.internal.pageSize.height - 10);

    // 5. Save the PDF
    doc.save(`${restaurantName}_Report_${date}.pdf`);
};